# Generated by Django 5.0.6 on 2024-07-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
