# Generated by Django 5.0.6 on 2024-07-12 17:50

from django.db import migrations
from projects.models import Project
from django.contrib.auth.models import User


def create_unassigned_project(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Project = apps.get_model("projects", "Project")

    for user in User.objects.all():
        Project.objects.get_or_create(
            name="Unassigned",
            owner=user
        )

class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_is_hidden"),
    ]

    operations = [
        migrations.RunPython(create_unassigned_project),
    ]
