# Generated by Django 5.0.6 on 2024-06-27 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("projects", "0003_company_project_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="companies.company",
            ),
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
