# Generated by Django 5.0.6 on 2024-07-09 17:06

from django.db import migrations, models


def set_company_null(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.all():
        project.company_id = None
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_company_delete_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(null=True, blank=True, to='companies.Company', on_delete=models.SET_NULL),
        ),
        migrations.RunPython(set_company_null),
    ]
