# Generated by Django 5.0.6 on 2024-07-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_taskchart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskChart",
        ),
    ]
