# Generated by Django 5.0.6 on 2024-06-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
